/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student1;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author w
 */
public class Addresult extends javax.swing.JFrame {
   /**
     * Creates new form Addresult
     */
    public Addresult() {
        initComponents();
            
            
             
        
    }
    
    void subjects(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cl = new javax.swing.JComboBox<>();
        rollno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        engText = new javax.swing.JTextField();
        matheText = new javax.swing.JTextField();
        hindiText = new javax.swing.JTextField();
        evsText = new javax.swing.JTextField();
        gkText = new javax.swing.JTextField();
        artText = new javax.swing.JTextField();
        peText = new javax.swing.JTextField();
        csText = new javax.swing.JTextField();
        sText = new javax.swing.JTextField();
        ssText = new javax.swing.JTextField();
        pText = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        pengText = new javax.swing.JTextField();
        pmatheText = new javax.swing.JTextField();
        phindiText = new javax.swing.JTextField();
        pevsText = new javax.swing.JTextField();
        pgkText = new javax.swing.JTextField();
        partText = new javax.swing.JTextField();
        ppeText = new javax.swing.JTextField();
        pcsText = new javax.swing.JTextField();
        psText = new javax.swing.JTextField();
        pssText = new javax.swing.JTextField();
        ppText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th" }));
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 16, 102, 33));

        rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoActionPerformed(evt);
            }
        });
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 16, 374, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Roll no");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 24, -1, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 16, -1, 33));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "class", "rollno", "aadharno"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 1088, 62));

        engText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                engTextKeyTyped(evt);
            }
        });
        getContentPane().add(engText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 194, 220, -1));

        matheText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matheTextActionPerformed(evt);
            }
        });
        matheText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matheTextKeyTyped(evt);
            }
        });
        getContentPane().add(matheText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 282, 220, -1));

        hindiText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hindiTextKeyTyped(evt);
            }
        });
        getContentPane().add(hindiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 358, 220, -1));

        evsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evsTextActionPerformed(evt);
            }
        });
        evsText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                evsTextKeyTyped(evt);
            }
        });
        getContentPane().add(evsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 426, 220, -1));

        gkText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gkTextKeyTyped(evt);
            }
        });
        getContentPane().add(gkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 500, 220, -1));

        artText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                artTextKeyTyped(evt);
            }
        });
        getContentPane().add(artText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 580, 220, -1));

        peText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                peTextKeyTyped(evt);
            }
        });
        getContentPane().add(peText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 194, 294, -1));

        csText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                csTextKeyTyped(evt);
            }
        });
        getContentPane().add(csText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 272, 294, -1));

        sText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTextActionPerformed(evt);
            }
        });
        sText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sTextKeyTyped(evt);
            }
        });
        getContentPane().add(sText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 353, 294, -1));

        ssText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ssTextKeyTyped(evt);
            }
        });
        getContentPane().add(ssText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 426, 294, -1));

        pText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pTextKeyTyped(evt);
            }
        });
        getContentPane().add(pText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 500, 294, -1));

        clear.setText("Clear");
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 635, -1, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 635, -1, -1));

        pengText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pengTextKeyTyped(evt);
            }
        });
        getContentPane().add(pengText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 194, 77, -1));

        pmatheText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmatheTextActionPerformed(evt);
            }
        });
        pmatheText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pmatheTextKeyTyped(evt);
            }
        });
        getContentPane().add(pmatheText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 282, 77, -1));

        phindiText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phindiTextKeyTyped(evt);
            }
        });
        getContentPane().add(phindiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 358, 77, -1));

        pevsText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pevsTextKeyTyped(evt);
            }
        });
        getContentPane().add(pevsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 426, 77, -1));

        pgkText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgkTextKeyTyped(evt);
            }
        });
        getContentPane().add(pgkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 500, 77, -1));

        partText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTextActionPerformed(evt);
            }
        });
        partText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                partTextKeyTyped(evt);
            }
        });
        getContentPane().add(partText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 580, 77, -1));

        ppeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ppeTextKeyTyped(evt);
            }
        });
        getContentPane().add(ppeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 194, 80, -1));

        pcsText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pcsTextKeyTyped(evt);
            }
        });
        getContentPane().add(pcsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 272, 80, -1));

        psText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psTextKeyTyped(evt);
            }
        });
        getContentPane().add(psText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 353, 80, -1));

        pssText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pssTextKeyTyped(evt);
            }
        });
        getContentPane().add(pssText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 426, 80, -1));

        ppText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ppTextKeyTyped(evt);
            }
        });
        getContentPane().add(ppText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 500, 80, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parctical");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 172, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parctical");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 172, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-page-option.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 16, 40, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("English");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 172, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mathematics");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 248, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hindi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 336, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enviromental Studies");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 392, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("General Knowledge");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 466, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Art and Craft");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 540, -1, 22));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Health and Physical Education");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 172, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Computer Science");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 250, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Science");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 325, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Social Science");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 392, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Punjabi");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 466, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 40, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 180, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Result");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PASS", "1st", "2nd", "3rd" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 190, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 60, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rg (1).jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoActionPerformed

    private void matheTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matheTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matheTextActionPerformed

    private void sTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTextActionPerformed

    private void pmatheTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmatheTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmatheTextActionPerformed

    private void partTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partTextActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    PreparedStatement pst=null;
    java.sql.Statement st=null;
    ResultSet rs=null;
    java.sql.Connection con=null; 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            pst=con.prepareStatement("Select * from student where class=? AND rollno=?");
            pst.setString(1,cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(2, rollno.getText());
            rs=pst.executeQuery();
            
            ResultSetMetaData stData=(ResultSetMetaData) rs.getMetaData();
            int q=stData.getColumnCount();
            DefaultTableModel RecordTable= (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while(rs.next()){
                //Vector is like the dynamic array.
                Vector columnData=new Vector();
                for(int i=1;i<=q;i++){
                    
                    columnData.add(rs.getString("name"));
                    columnData.add(rs.getString("class"));
                    columnData.add(rs.getString("rollno"));
                    columnData.add(rs.getString("aadharnumber"));
   
                }
                RecordTable.addRow(columnData);
                //System.out.println(columnData);

            }  
        } catch (ClassNotFoundException | SQLException ex) {}  
   if(cl.getSelectedItem().equals("1st") || cl.getSelectedItem().equals("2nd")){  
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            pst=con.prepareStatement("Select * from resulte1st2nd where class=? AND rollno=?");
            pst.setString(1,cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(2, rollno.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                    int yes=JOptionPane.showConfirmDialog(this,"Resulte is allready available.\nDo you want to Update Resulte?","update",JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION==yes)
                new Showresulte().setVisible(true);
            }
         } catch (ClassNotFoundException | SQLException ex) {} 
       
         evsText.setEditable(false);
         pevsText.setEditable(false);
         peText.setEditable(false);
         ppeText.setEditable(false);
         csText.setEditable(false);
         pcsText.setEditable(false);
         sText.setEditable(false);
         psText.setEditable(false);
         ssText.setEditable(false);
         pssText.setEditable(false);
         pText.setEditable(false);
         ppText.setEditable(false);
         
          
   }  
   else if (cl.getSelectedItem().equals("3rd") || cl.getSelectedItem().equals("4th")) {
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            pst=con.prepareStatement("Select * from resulte3rd4th where class=? AND rollno=?");
            pst.setString(1,cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(2, rollno.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                    int yes=JOptionPane.showConfirmDialog(this,"Resulte is allready available.\nDo you want to Update Resulte?","update",JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION==yes)
                new Showresulte().setVisible(true);
            }
         } catch (ClassNotFoundException | SQLException ex) {} 
       
         artText.setEditable(false);
         partText.setEditable(false);
         peText.setEditable(false);
         ppeText.setEditable(false);
         csText.setEditable(false);
         pcsText.setEditable(false);
         sText.setEditable(false);
         psText.setEditable(false);
         ssText.setEditable(false);
         pssText.setEditable(false);
         pText.setEditable(false);
         ppText.setEditable(false);
   
        }
   else if (cl.getSelectedItem().equals("5th") || cl.getSelectedItem().equals("6th")) {
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            pst=con.prepareStatement("Select * from resulte5th6th where class=? AND rollno=?");
            pst.setString(1,cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(2, rollno.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                    int yes=JOptionPane.showConfirmDialog(this,"Resulte is allready available.\nDo you want to Update Resulte?","update",JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION==yes)
                new Showresulte().setVisible(true);
            }
         } catch (ClassNotFoundException | SQLException ex) {} 
       
         artText.setEditable(false);
         partText.setEditable(false);
         gkText.setEditable(false);
         pgkText.setEditable(false);
         peText.setEditable(false);
         ppeText.setEditable(false);
         csText.setEditable(false);
         pcsText.setEditable(false);
         pText.setEditable(false);
         ppText.setEditable(false);
    
        }
   else if (cl.getSelectedItem().equals("7th") || cl.getSelectedItem().equals("8th")) {
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            pst=con.prepareStatement("Select * from resulte7th8th where class=? AND rollno=?");
            pst.setString(1,cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(2, rollno.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                    int yes=JOptionPane.showConfirmDialog(this,"Resulte is allready available.\nDo you want to Update Resulte?","update",JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION==yes)
                new Showresulte().setVisible(true);
            }
         } catch (ClassNotFoundException | SQLException ex) {} 
       
         artText.setEditable(false);
         partText.setEditable(false);
         gkText.setEditable(false);
         pgkText.setEditable(false);
         evsText.setEditable(false);
         pevsText.setEditable(false);
         peText.setEditable(false);
         ppeText.setEditable(false);
         csText.setEditable(false);
         pcsText.setEditable(false);
         pText.setEditable(false);
         ppText.setEditable(false);
   
        }
   else if (cl.getSelectedItem().equals("9th") || cl.getSelectedItem().equals("10th")) {
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            pst=con.prepareStatement("Select * from resulte9th10th where class=? AND rollno=?");
            pst.setString(1,cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(2, rollno.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                    int yes=JOptionPane.showConfirmDialog(this,"Resulte is allready available.\nDo you want to Update Resulte?","update",JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION==yes)
                new Showresulte().setVisible(true);
            }
         } catch (ClassNotFoundException | SQLException ex) {} 
       
        
         artText.setEditable(false);
         partText.setEditable(false);
         gkText.setEditable(false);
         pgkText.setEditable(false);
         evsText.setEditable(false);
         pevsText.setEditable(false);
         csText.setEditable(false);
         pcsText.setEditable(false);
         pText.setEditable(false);
         ppText.setEditable(false);
   
       
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable= (DefaultTableModel) jTable1.getModel();
        RecordTable.setRowCount(0);
        rollno.setText(null);
        cl.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        Statement st=null;
        PreparedStatement pst=null;
        
        String name= jTable1.getValueAt(0, 0).toString() ;
        String clas= jTable1.getValueAt(0, 1).toString() ;
        String roll= jTable1.getValueAt(0, 2).toString() ;
        String addh= jTable1.getValueAt(0, 3).toString() ;
      
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
 
         if(cl.getSelectedItem().equals("1st") || cl.getSelectedItem().equals("2nd")){
             
          pst=con.prepareStatement("insert into resulte1st2nd(name,class,rollno,aadharnumber,Eng,hindi,Math,Art,GK,peng,phindi,pmath,part,pgk,total,resulte)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
          pst.setString(1, name);
            pst.setString(2, clas);
            pst.setString(3, roll);
            pst.setString(4,addh);
            pst.setString(5,engText.getText());
            pst.setString(6, hindiText.getText());
            pst.setString(7,matheText.getText());
            pst.setString(8,artText.getText());
            pst.setString(9,gkText.getText());
            pst.setString(10, pengText.getText());
            pst.setString(11, phindiText.getText());
            pst.setString(12, pmatheText.getText());
            pst.setString(13,partText.getText());
            pst.setString(14,pgkText.getText());
            pst.setString(15,jTextField1.getText());
            pst.setString(16,jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
         }
         else if (cl.getSelectedItem().equals("3rd") || cl.getSelectedItem().equals("4th")){
            pst=con.prepareStatement("insert into resulte3rd4th(name,class,rollno,aadharnumber,Eng,hindi,Math,GK,evs,peng,phindi,pmath,pgk,pevs,total,resulte)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, name);
            pst.setString(2, clas);
            pst.setString(3, roll);
            pst.setString(4,addh);
            pst.setString(5,engText.getText());
            pst.setString(6, hindiText.getText());
            pst.setString(7,matheText.getText());
            pst.setString(8,gkText.getText());
            pst.setString(9,evsText.getText());
            pst.setString(10, pengText.getText());
            pst.setString(11, phindiText.getText());
            pst.setString(12, pmatheText.getText());
            pst.setString(13,pgkText.getText());
            pst.setString(14,pevsText.getText());
             pst.setString(15,jTextField1.getText());
            pst.setString(16,jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved"); 
            
           
         } 
         else if (cl.getSelectedItem().equals("5th") || cl.getSelectedItem().equals("6th")){
              pst=con.prepareStatement("insert into resulte5th6th(name,class,rollno,aadharnumber,Eng,hindi,Math,Science,evs,socialscience,peng,phindi,pmath,pscience,pevs,psocialscience,total,resulte)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
          pst.setString(1, name);
            pst.setString(2, clas);
            pst.setString(3, roll);
            pst.setString(4,addh);
            pst.setString(5,engText.getText());
            pst.setString(6, hindiText.getText());
            pst.setString(7,matheText.getText());
            pst.setString(8,sText.getText());
            pst.setString(9,evsText.getText());
            pst.setString(10, ssText.getText());
            pst.setString(11, pengText.getText());
            pst.setString(12, phindiText.getText());
            pst.setString(13,pmatheText.getText());
            pst.setString(14,psText.getText());
            pst.setString(15,pevsText.getText());
            pst.setString(16,pssText.getText());
            pst.setString(17,jTextField1.getText());
            pst.setString(18,jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
         }
         else if (cl.getSelectedItem().equals("7th") || cl.getSelectedItem().equals("8th")){
              pst=con.prepareStatement("insert into resulte7th8th(name,class,rollno,aadharnumber,Eng,hindi,Math,Science,socialscience,peng,phindi,pmath,pscience,psocialscience,total,resulte)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
          pst.setString(1, name);
            pst.setString(2, clas);
            pst.setString(3, roll);
            pst.setString(4,addh);
            pst.setString(5,engText.getText());
            pst.setString(6, hindiText.getText());
            pst.setString(7,matheText.getText());
            pst.setString(8,sText.getText());
            pst.setString(9,ssText.getText());
            pst.setString(10, pengText.getText());
            pst.setString(11, phindiText.getText());
            pst.setString(12, pmatheText.getText());
            pst.setString(13,psText.getText());
            pst.setString(14,pssText.getText());
            pst.setString(15,jTextField1.getText());
            pst.setString(16,jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
         }
         else if (cl.getSelectedItem().equals("9th") || cl.getSelectedItem().equals("10th")){
              pst=con.prepareStatement("insert into resulte9th10th(name,class,rollno,aadharnumber,Eng,hindi,Math,Science,socialscience,physicaleducation,peng,phindi,pmath,pscience,psocialscience,pphysicaleducation,total,resulte)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
          pst.setString(1, name);
            pst.setString(2, clas);
            pst.setString(3, roll);
            pst.setString(4,addh);
            pst.setString(5,engText.getText());
            pst.setString(6, hindiText.getText());
            pst.setString(7,matheText.getText());
            pst.setString(8,sText.getText());
            pst.setString(9,ssText.getText());
            pst.setString(10,peText.getText());
            pst.setString(11, pengText.getText());
            pst.setString(12, phindiText.getText());
            pst.setString(13, pmatheText.getText());
            pst.setString(14,psText.getText());
            pst.setString(15,pssText.getText());
            pst.setString(16,ppeText.getText());
            pst.setString(17,jTextField1.getText());
            pst.setString(18,jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
         } 
         } 
    
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_saveActionPerformed

    private void evsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evsTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        homepage hm = new homepage();
        hm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
             
         if(cl.getSelectedItem().equals("1st") || cl.getSelectedItem().equals("2nd")){
             int m1= Integer.parseInt(engText.getText());
             int m2= Integer.parseInt(hindiText.getText());
             int m3= Integer.parseInt(matheText.getText());
             int m4= Integer.parseInt(artText.getText());
             int m5= Integer.parseInt(gkText.getText());
             int m6= Integer.parseInt(pengText.getText());
             int m7= Integer.parseInt(phindiText.getText());
             int m8= Integer.parseInt(pmatheText.getText());
             int m9= Integer.parseInt(partText.getText());
             int m10= Integer.parseInt(pgkText.getText());
            
             int result = m1+m2+m3+m4+m5+m6+m7+m8+m9+m10 ;
             jTextField1.setText(String.valueOf(result));
         }
         else if (cl.getSelectedItem().equals("3rd") || cl.getSelectedItem().equals("4th")){
             int m1= Integer.parseInt(engText.getText());
             int m2= Integer.parseInt(hindiText.getText());
             int m3= Integer.parseInt(matheText.getText());  
             int m5= Integer.parseInt(gkText.getText());
             int m6= Integer.parseInt(pengText.getText());
             int m7= Integer.parseInt(phindiText.getText());
             int m8= Integer.parseInt(pmatheText.getText());
             int m10= Integer.parseInt(pgkText.getText());
             int m11= Integer.parseInt(evsText.getText());
             int m12= Integer.parseInt(pevsText.getText());
          
     
             int result = m1+m2+m3+m5+m6+m7+m8+m10+m11+m12 ;
            jTextField1.setText(String.valueOf(result));
         } 
         else if (cl.getSelectedItem().equals("5th") || cl.getSelectedItem().equals("6th")){
             int m1= Integer.parseInt(engText.getText());
             int m2= Integer.parseInt(hindiText.getText());
             int m3= Integer.parseInt(matheText.getText());
             int m6= Integer.parseInt(pengText.getText());
             int m7= Integer.parseInt(phindiText.getText());
             int m8= Integer.parseInt(pmatheText.getText());
             int m11= Integer.parseInt(evsText.getText());
             int m12= Integer.parseInt(pevsText.getText());
             int m19= Integer.parseInt(ssText.getText());
             int m20= Integer.parseInt(pssText.getText());
             int result = m1+m2+m3+m6+m7+m8+m11+m12+m19+m20 ;
            jTextField1.setText(String.valueOf(result));
         }
         else if (cl.getSelectedItem().equals("7th") || cl.getSelectedItem().equals("8th")){
             int m1= Integer.parseInt(engText.getText());
             int m2= Integer.parseInt(hindiText.getText());
             int m3= Integer.parseInt(matheText.getText());
             int m6= Integer.parseInt(pengText.getText());
             int m7= Integer.parseInt(phindiText.getText());
             int m8= Integer.parseInt(pmatheText.getText());
             int m17= Integer.parseInt(sText.getText());
             int m18= Integer.parseInt(psText.getText());
             int m19= Integer.parseInt(ssText.getText());
             int m20= Integer.parseInt(pssText.getText());
               int result = m1+m2+m3+m6+m7+m8+m19+m20+m17+m18 ;
            jTextField1.setText(String.valueOf(result));
}
         else if (cl.getSelectedItem().equals("9th") || cl.getSelectedItem().equals("10th")){
             int m1= Integer.parseInt(engText.getText());
             int m2= Integer.parseInt(hindiText.getText());
             int m3= Integer.parseInt(matheText.getText());
             int m6= Integer.parseInt(pengText.getText());
             int m7= Integer.parseInt(phindiText.getText());
             int m8= Integer.parseInt(pmatheText.getText());
             int m13= Integer.parseInt(peText.getText());
             int m14= Integer.parseInt(ppeText.getText());
             int m17= Integer.parseInt(sText.getText());
             int m18= Integer.parseInt(psText.getText());
             int m19= Integer.parseInt(ssText.getText());
             int m20= Integer.parseInt(pssText.getText());
                int result = m1+m2+m3+m6+m7+m8+m19+m20+m17+m18+m13+m14;
            jTextField1.setText(String.valueOf(result));
         } 
         
    
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void engTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_engTextKeyTyped
        // TODO add your handling code here:
        char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(engText.getText().length()>1)
        {
            evt.consume();
        }
         
    }//GEN-LAST:event_engTextKeyTyped

    private void pengTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pengTextKeyTyped
        // TODO add your handling code here:
           char k=evt.getKeyChar();
        if(!(Character.isDigit(k)))
        {
            evt.consume();
        }
        if(pengText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pengTextKeyTyped

    private void matheTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matheTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(matheText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_matheTextKeyTyped

    private void pmatheTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pmatheTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(pmatheText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pmatheTextKeyTyped

    private void hindiTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hindiTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(hindiText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_hindiTextKeyTyped

    private void phindiTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phindiTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(phindiText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_phindiTextKeyTyped

    private void evsTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_evsTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(evsText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_evsTextKeyTyped

    private void pevsTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pevsTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(pevsText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pevsTextKeyTyped

    private void gkTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gkTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(gkText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_gkTextKeyTyped

    private void pgkTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgkTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(pgkText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pgkTextKeyTyped

    private void artTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_artTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(artText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_artTextKeyTyped

    private void partTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_partTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(partText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_partTextKeyTyped

    private void peTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_peTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(peText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_peTextKeyTyped

    private void ppeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppeTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(ppeText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_ppeTextKeyTyped

    private void csTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(csText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_csTextKeyTyped

    private void pcsTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcsTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(pcsText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pcsTextKeyTyped

    private void sTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(sText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_sTextKeyTyped

    private void psTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(psText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_psTextKeyTyped

    private void ssTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(ssText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_ssTextKeyTyped

    private void pssTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pssTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(pssText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pssTextKeyTyped

    private void pTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(pText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_pTextKeyTyped

    private void ppTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppTextKeyTyped
        // TODO add your handling code here:
           char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(ppText.getText().length()>1)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_ppTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addresult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artText;
    private javax.swing.JComboBox<String> cl;
    private javax.swing.JButton clear;
    private javax.swing.JTextField csText;
    private javax.swing.JTextField engText;
    private javax.swing.JTextField evsText;
    private javax.swing.JTextField gkText;
    private javax.swing.JTextField hindiText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField matheText;
    private javax.swing.JTextField pText;
    private javax.swing.JTextField partText;
    private javax.swing.JTextField pcsText;
    private javax.swing.JTextField peText;
    private javax.swing.JTextField pengText;
    private javax.swing.JTextField pevsText;
    private javax.swing.JTextField pgkText;
    private javax.swing.JTextField phindiText;
    private javax.swing.JTextField pmatheText;
    private javax.swing.JTextField ppText;
    private javax.swing.JTextField ppeText;
    private javax.swing.JTextField psText;
    private javax.swing.JTextField pssText;
    private javax.swing.JTextField rollno;
    private javax.swing.JTextField sText;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField ssText;
    // End of variables declaration//GEN-END:variables
}
