/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student1;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.*;
/**
 *
 * @author pc
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stdname = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mothername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        aadhar = new javax.swing.JTextField();
        saveinfo = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        religion = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        fatherocc = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        cl = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        st = new javax.swing.JComboBox<>();
        ci = new javax.swing.JComboBox<>();
        nationality = new javax.swing.JComboBox<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_img = new javax.swing.JLabel();
        addphoto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("STUDENT ADMISSION FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("STUDENT NAME :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 82, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setText("CLASS :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 282, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setText("DOB :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 231, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setText("GENDER :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 329, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("EMAIL ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("CONTACT NUMBER :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 371, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setText("ADDRESS :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        stdname.setToolTipText("Please enter alphabets only");
        stdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdnameActionPerformed(evt);
            }
        });
        stdname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stdnameKeyTyped(evt);
            }
        });
        jPanel1.add(stdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 85, 246, 33));

        fathername.setToolTipText("enter alphabets only");
        fathername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernameActionPerformed(evt);
            }
        });
        fathername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fathernameKeyTyped(evt);
            }
        });
        jPanel1.add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 126, 246, 35));

        contactno.setToolTipText("enter digits only");
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        contactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnoKeyTyped(evt);
            }
        });
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 375, 250, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 243, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setText("AADHAR NUMBER :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        mothername.setToolTipText("enter alphabets only");
        mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernameActionPerformed(evt);
            }
        });
        mothername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mothernameKeyTyped(evt);
            }
        });
        jPanel1.add(mothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 183, 249, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel10.setText("NATIONALITY :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel12.setText("PIN CODE :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 507, -1, 34));

        pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinMouseEntered(evt);
            }
        });
        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinKeyTyped(evt);
            }
        });
        jPanel1.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 511, 250, 34));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel13.setText("STATE :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 411, -1, 34));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel14.setText("CITY :");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 455, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel15.setText("FATHER'S NAME :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel16.setText("MOTHER'S NAME :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 179, 201, -1));

        aadhar.setToolTipText("enter digits only");
        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        aadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aadharKeyTyped(evt);
            }
        });
        jPanel1.add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 243, 30));

        saveinfo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        saveinfo.setText("SAVE");
        saveinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveinfoActionPerformed(evt);
            }
        });
        jPanel1.add(saveinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 730, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 40, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel19.setText("CASTE :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "SC", "ST", "OBC", "GEN" }));
        religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionActionPerformed(evt);
            }
        });
        jPanel1.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 243, 38));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel20.setText("FATHER'S OCCUPATION :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        fatherocc.setToolTipText("enter alphabets only");
        fatherocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatheroccActionPerformed(evt);
            }
        });
        fatherocc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatheroccKeyTyped(evt);
            }
        });
        jPanel1.add(fatherocc, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 246, 37));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "MALE", "FEMALE", "OTHER", " " }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 331, 249, 34));

        cl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th" }));
        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 279, 249, 33));

        dob.setDateFormatString("yyyy-MM-dd"); // NOI18N
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 231, 249, 30));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, -1, 120));

        st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "Punjab", "Himachal Pradesh", "Jammu and kashmir", "Haryana" }));
        st.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stMouseEntered(evt);
            }
        });
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel1.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 415, 250, 34));

        ci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE" }));
        ci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ciMouseEntered(evt);
            }
        });
        ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciActionPerformed(evt);
            }
        });
        jPanel1.add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 459, 250, 30));

        nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "Indian", "Canadian", "South Korean", "Australian" }));
        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });
        jPanel1.add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 243, 30));

        jDesktopPane1.setLayer(lbl_img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, -1, -1));

        addphoto.setText("Add Photo");
        addphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addphotoActionPerformed(evt);
            }
        });
        jPanel1.add(addphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 250, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dom-fou-YRMWVcdyhmI-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdnameActionPerformed

    private void fathernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathernameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void saveinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveinfoActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement pst;
        ResultSet rs;
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
        String date= sf.format(dob.getDate());
        
        if(stdname.getText().equals("")){
      JOptionPane.showMessageDialog(this, "All Field is Requied");
      stdname.requestFocus();
    }
    else if(fathername.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       fathername.requestFocus();
    }
    
     else if(mothername.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       mothername.requestFocus();
    }
     else if(email.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       email.requestFocus();
    }
     else if(nationality.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Nationality");
       nationality.requestFocus();
     }
     else if(cl.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Class");
       cl.requestFocus();
     }
     else if(gender.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Gender");
       gender.requestFocus();
     }
     else if(st.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select State");
       st.requestFocus();
     }
     else if(ci.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select City");
       ci.requestFocus();
     }
     else if(religion.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Cast");
       religion.requestFocus();
     }
     else if(address.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       address.requestFocus();
    }
     else if(fatherocc.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       fatherocc.requestFocus();
    }
     else if(pin.getText().length()!=6){
        JOptionPane.showMessageDialog(this, "pincode Should be 6 Digit.");
    }
    else if(aadhar.getText().length()!=12){
        JOptionPane.showMessageDialog(this, "Adhar Number Should be 12 Digit.");
     }
     else if(contactno.getText().length()!=10){
        JOptionPane.showMessageDialog(this, "Mobile Number Should be 10 Digit.");
     }
    
    else{ 
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            
            
if(cl.getSelectedItem().equals("1st")){
    pst=con.prepareStatement("insert into 1st(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 1st where aadharnumber=?");
            pst.setString(1, aadhar.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("2nd")){
     pst=con.prepareStatement("insert into 2nd(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"saved");
            
            pst =con.prepareStatement("insert into student select * from 2nd where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("3rd")){
     pst=con.prepareStatement("insert into 3rd(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"saved");
            
            pst =con.prepareStatement("insert into student select * from 3rd where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("4th")){
     pst=con.prepareStatement("insert into 4th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 4th where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("5th")){
     pst=con.prepareStatement("insert into 5th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 5th where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("6th")){
    pst=con.prepareStatement("insert into 6th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 6th where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("7th")){
     pst=con.prepareStatement("insert into 7th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 7th where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("8th")){
     pst=con.prepareStatement("insert into 8th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 8th where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("9th")){
     pst=con.prepareStatement("insert into 9th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 9th where email=?");
            pst.setString(1, email.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("10th")){
     pst=con.prepareStatement("insert into 10th(fathername,mothername,class,dob,contact,email,religion,aadharnumber,nationality,gender,state,city,pin,address,fatheroccupation,name,studentimg)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3, cl.getItemAt(cl.getSelectedIndex()));
            pst.setString(4,date);
            pst.setString(5,contactno.getText());
            pst.setString(6, email.getText());
            pst.setString(7,(String) religion.getSelectedItem());
            pst.setString(8,aadhar.getText());
            pst.setString(9,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(10, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(11, st.getItemAt(st.getSelectedIndex()));
            pst.setString(12, ci.getItemAt(ci.getSelectedIndex()));
            pst.setString(13,pin.getText());
            pst.setString(14,address.getText());
            pst.setString(15, fatherocc.getText());
            pst.setString(16, stdname.getText());
            pst.setBytes(17,studentimg);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "saved");
            
            pst =con.prepareStatement("insert into student select * from 10th where aadharnumber=?");
            pst.setString(1, aadhar.getText());
            pst.executeUpdate();
}

else{
    JOptionPane.showMessageDialog(this,"STUDENT DATA NOT ADDED INTO CLASS");
}

        }    
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
       
    }//GEN-LAST:event_saveinfoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        homepage l= new homepage();
        l.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void stdnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdnameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if((Character.isDigit(c)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_stdnameKeyTyped

    private void fathernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fathernameKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if((Character.isDigit(a)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_fathernameKeyTyped

    private void fatheroccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatheroccKeyTyped
        // TODO add your handling code here:
        char b=evt.getKeyChar();
        if((Character.isDigit(b)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_fatheroccKeyTyped

    private void mothernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mothernameKeyTyped
        // TODO add your handling code here:
        char d=evt.getKeyChar();
        if((Character.isDigit(d)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_mothernameKeyTyped

    private void contactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyTyped
        // TODO add your handling code here:
        char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(contactno.getText().length()>9)
        {
            evt.consume();
        }
         if(contactno.getText().length()<9)
         {
            contactno.setBackground(Color.red);
         }    
         if(contactno.getText().length()==9)
         {
        contactno.setBackground(Color.green);
         }
    }//GEN-LAST:event_contactnoKeyTyped

    private void pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyTyped
        // TODO add your handling code here:
      char k=evt.getKeyChar();
        if(!(Character.isDigit(k)))
        {
            evt.consume();
        } 
        if(pin.getText().length()>5)
        {
            evt.consume();
        }
         if(pin.getText().length()<5)
         {
            pin.setBackground(Color.red);
         }    
         if(pin.getText().length()==5)
         {
        pin.setBackground(Color.green);
         }        

    }//GEN-LAST:event_pinKeyTyped

    private void aadharKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aadharKeyTyped
        // TODO add your handling code here:
        char l=evt.getKeyChar();
        if(!(Character.isDigit(l)))
        {
            evt.consume();
        }
        if(aadhar.getText().length()>11)
        {
            evt.consume();
        }
         if(aadhar.getText().length()<11)
         {
            aadhar.setBackground(Color.red);
         }    
         if(aadhar.getText().length()==11)
         {
        aadhar.setBackground(Color.green);
         }        
    }//GEN-LAST:event_aadharKeyTyped

    private void religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionActionPerformed

    private void mothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernameActionPerformed

    private void ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciActionPerformed
 try
{
        
        if(ci.getSelectedItem().equals("Pathankot"))
{
    pin.setText("");
    pin.setText("145001");
}
    else
      if(ci.getSelectedItem().equals("Amritsar"))
{
    pin.setText("");
    pin.setText("143001");     
}  
    else
      if(ci.getSelectedItem().equals("Jalandhar"))
{
    pin.setText("");
    pin.setText("144001");
}
    else
      if(ci.getSelectedItem().equals("Ludhiana"))
{
    pin.setText("");
    pin.setText("141001");
}
    else
      if(ci.getSelectedItem().equals("Patiala"))
{
    pin.setText("");
    pin.setText("147001");
}
    else
      if(ci.getSelectedItem().equals("Hoshiarpur"))
{
    pin.setText("");
    pin.setText("146001");
}
    else
      if(ci.getSelectedItem().equals("Chamba"))
{
    pin.setText("");
    pin.setText("176310");
}
    else
      if(ci.getSelectedItem().equals("Dharamshala"))
{
    pin.setText("");
    pin.setText("176215");
}
    else
      if(ci.getSelectedItem().equals("Shimla"))
{
    pin.setText("");
    pin.setText("171001");
}
    else
      if(ci.getSelectedItem().equals("Manali"))
{
    pin.setText("");
    pin.setText("175131");
}
    else
       if(ci.getSelectedItem().equals("Solan"))
{
    pin.setText("");
    pin.setText("173212");
}
    else
       if(ci.getSelectedItem().equals("Dalhousie"))
{
    pin.setText("");
    pin.setText("176304");
}
    else
       if(ci.getSelectedItem().equals("Kullu"))
{
    pin.setText("");
    pin.setText("175101");
}
    else
       if(ci.getSelectedItem().equals("Jammu"))
{
    pin.setText("");
    pin.setText("180001");
}
    else
       if(ci.getSelectedItem().equals("Katra"))
{
    pin.setText("");
    pin.setText("182320");
}
    else
       if(ci.getSelectedItem().equals("Khang"))
{
    pin.setText("");
    pin.setText("143406");
}
    else
       if(ci.getSelectedItem().equals("Kulgam"))
{
    pin.setText("");
    pin.setText("192231");
}
    else
       if(ci.getSelectedItem().equals("Anantnag"))
{
    pin.setText("");
    pin.setText("192122");
}   
    else
       if(ci.getSelectedItem().equals("Surankoti"))
{
    pin.setText("");
    pin.setText("144702");
}
    else
        if(ci.getSelectedItem().equals("Poonch"))
{
    pin.setText("");
    pin.setText("185101");
}
    else
        if(ci.getSelectedItem().equals("Akhnoor"))
{
    pin.setText("");
    pin.setText("181201");
}
    else
        if(ci.getSelectedItem().equals("Rohtak"))
{
    pin.setText("");
    pin.setText("124001");
}
    else
        if(ci.getSelectedItem().equals("Faridabad"))
{
    pin.setText("");
    pin.setText("121002");
}
    else
        if(ci.getSelectedItem().equals("Ambala"))
{
    pin.setText("");
    pin.setText("134003");
}
    else
        if(ci.getSelectedItem().equals("Sonipat"))
{
    pin.setText("");
    pin.setText("131001");
}
    else
        if(ci.getSelectedItem().equals("Hisar"))
{
    pin.setText("");
    pin.setText("125001");
}
}
catch(Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_ciActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
    try
    {
     if(st.getSelectedItem().equals("Punjab"))
    {
            ci.removeAllItems();
            ci.addItem("Pathankot");
            ci.addItem("Amritsar");
            ci.addItem("Jalandhar");
            ci.addItem("Ludhiana");
            ci.addItem("Patiala");
            ci.addItem("Hoshiarpur");
    }
     else if(st.getSelectedItem().equals("Himachal Pradesh"))
        {
            ci.removeAllItems();
            ci.addItem("Chamba");
            ci.addItem("Dharamshala");
            ci.addItem("Shimla");
            ci.addItem("Manali");
            ci.addItem("Solan");
            ci.addItem("Dalhousie");
            ci.addItem("Kullu");
        } 
     else if(st.getSelectedItem().equals("Jammu and kashmir"))
       {
            ci.removeAllItems();
            ci.addItem("Jammu");
            ci.addItem("Katra");
            ci.addItem("Khang");
            ci.addItem("Kulgam");
            ci.addItem("Anantnag");
            ci.addItem("Surankote");
            ci.addItem("Poonch");
            ci.addItem("Akhnoor");   
       } 
     else if(st.getSelectedItem().equals("Haryana"))
       {
            ci.addItem("Rohtak");
            ci.addItem("Faridabad");
            ci.addItem("Ambala");
            ci.addItem("Sonipat");
            ci.addItem("Hisar");
    }                               
     }
  catch(Exception e){
      System.out.println(e);
  }
    }//GEN-LAST:event_stActionPerformed

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityActionPerformed

    private void fatheroccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatheroccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatheroccActionPerformed

    private void ciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciMouseEntered
    
        /*if(ci.getSelectedItem().equals("Pathankot"))
   {
    pin.setText("");
    pin.setText("145001");
   }
   if(ci.getSelectedItem().equals("Amritsar"))
   {
    pin.setText("");
    pin.setText("143001");
   }*/
    }//GEN-LAST:event_ciMouseEntered
    
    private void pinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinMouseEntered
        // TODO add your handling code here:
        
     
        
    }//GEN-LAST:event_pinMouseEntered

    private void stMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stMouseEntered
/*if(st.getSelectedItem().equals("Punjab"))
        {
            ci.removeAllItems();
            ci.addItem("Pathankot");
            ci.addItem("Amritsar");
            ci.addItem("Jalandhar");
            ci.addItem("Ludhiana");
            ci.addItem("Patiala");
            ci.addItem("Hoshiarpur");
    }
                   
     if(st.getSelectedItem().equals("Himachal Pradesh"))
     {
            ci.removeAllItems();
            ci.addItem("Chamba");
            ci.addItem("Dharamshala");
            ci.addItem("Shimla");
            ci.addItem("Manali");
            ci.addItem("Solan");
            ci.addItem("Dalhousie");
            ci.addItem("Kullu");
     }
       if(st.getSelectedItem().equals("Jammu and Kashmir"))
       {
            ci.removeAllItems();
            ci.addItem("Jammu");
            ci.addItem("Katra");
            ci.addItem("Khang");
            ci.addItem("Kulgam");
            ci.addItem("Anantnag");
            ci.addItem("Surankote");
            ci.addItem("Poonch");
            ci.addItem("Akhnoor");   
       }*/
    }//GEN-LAST:event_stMouseEntered

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void stMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stMouseClicked
   /* try
    {
     if(st.getSelectedItem().equals("Punjab"))
    {
            ci.removeAllItems();
            ci.addItem("Pathankot");
            ci.addItem("Amritsar");
            ci.addItem("Jalandhar");
            ci.addItem("Ludhiana");
            ci.addItem("Patiala");
            ci.addItem("Hoshiarpur");
    }
     else              
     if(st.getSelectedItem().equals("Himachal Pradesh"))
     {
            ci.removeAllItems();
            ci.addItem("Chamba");
            ci.addItem("Dharamshala");
            ci.addItem("Shimla");
            ci.addItem("Manali");
            ci.addItem("Solan");
            ci.addItem("Dalhousie");
            ci.addItem("Kullu");
     } 
     else
       if(st.getSelectedItem().equals("Jammu and Kashmir"))
       {
            ci.removeAllItems();
            ci.addItem("Jammu");
            ci.addItem("Katra");
            ci.addItem("Khang");
            ci.addItem("Kulgam");
            ci.addItem("Anantnag");
            ci.addItem("Surankote");
            ci.addItem("Poonch");
            ci.addItem("Akhnoor");   
       } 
     else
       if(st.getSelectedItem().equals("Haryana"))
       {
            ci.addItem("Rohtak");
            ci.addItem("Faridabad");
            ci.addItem("Ambala");
            ci.addItem("Sonipat");
            ci.addItem("Hisar");
    }//GEN-LAST:event_stMouseClicked
     }
  catch(Exception e){
      System.out.println(e);
  }*/
    }   
    private void ciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciMouseClicked
/*if(ci.getSelectedItem().equals("Pathankot"))
{
    pin.setText("");
    pin.setText("145001");
}
if(ci.getSelectedItem().equals("Amritsar"))
{
    pin.setText("");
    pin.setText("143001");     
    }//GEN-LAST:event_ciMouseClicked
  if(ci.getSelectedItem().equals("Jalandhar"))
{
    pin.setText("");
    pin.setText("144001");
}
if(ci.getSelectedItem().equals("Ludhiana"))
{
    pin.setText("");
    pin.setText("141001");
}
if(ci.getSelectedItem().equals("Patiala"))
{
    pin.setText("");
    pin.setText("147001");
}
if(ci.getSelectedItem().equals("Hoshiarpur"))
{
    pin.setText("");
    pin.setText("146001");
}
if(ci.getSelectedItem().equals("Chamba"))
{
    pin.setText("");
    pin.setText("176310");
}
if(ci.getSelectedItem().equals("Dharamshala"))
{
    pin.setText("");
    pin.setText("176215");
}
if(ci.getSelectedItem().equals("Shimla"))
{
    pin.setText("");
    pin.setText("171001");
}
if(ci.getSelectedItem().equals("Manali"))
{
    pin.setText("");
    pin.setText("175131");
}
if(ci.getSelectedItem().equals("Solan"))
{
    pin.setText("");
    pin.setText("173212");
}
if(ci.getSelectedItem().equals("Dalhousie"))
{
    pin.setText("");
    pin.setText("176304");
}
if(ci.getSelectedItem().equals("Kullu"))
{
    pin.setText("");
    pin.setText("175101");
}
if(ci.getSelectedItem().equals("Jammu"))
{
    pin.setText("");
    pin.setText("180001");
}
if(ci.getSelectedItem().equals("Katra"))
{
    pin.setText("");
    pin.setText("182320");
}
if(ci.getSelectedItem().equals("Khang"))
{
    pin.setText("");
    pin.setText("143406");
}
if(ci.getSelectedItem().equals("Kulgam"))
{
    pin.setText("");
    pin.setText("192231");
}
if(ci.getSelectedItem().equals("Anantnag"))
{
    pin.setText("");
    pin.setText("192122");
}
if(ci.getSelectedItem().equals("Surankoti"))
{
    pin.setText("");
    pin.setText("144702");
}
if(ci.getSelectedItem().equals("Poonch"))
{
    pin.setText("");
    pin.setText("185101");
}
if(ci.getSelectedItem().equals("Akhnoor"))
{
    pin.setText("");
    pin.setText("181201");
}
if(ci.getSelectedItem().equals("Rohtak"))
{
    pin.setText("");
    pin.setText("124001");
}
if(ci.getSelectedItem().equals("Faridabad"))
{
    pin.setText("");
    pin.setText("121002");
}
if(ci.getSelectedItem().equals("Ambala"))
{
    pin.setText("");
    pin.setText("134003");
}
if(ci.getSelectedItem().equals("Sonipat"))
{
    pin.setText("");
    pin.setText("131001");
}
if(ci.getSelectedItem().equals("Hisar"))
{
    pin.setText("");
    pin.setText("125001");
} */  
    }
    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
   
    }//GEN-LAST:event_pinActionPerformed

    private void addphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addphotoActionPerformed
        // TODO add your handling code here:
          JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
        lbl_img.setIcon(imageIcon);
      try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
             studentimg = bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_addphotoActionPerformed
   
 
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JButton addphoto;
    private javax.swing.JTextArea address;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> ci;
    private javax.swing.JComboBox<String> cl;
    private javax.swing.JTextField contactno;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fathername;
    private javax.swing.JTextField fatherocc;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField mothername;
    private javax.swing.JComboBox<String> nationality;
    private javax.swing.JTextField pin;
    private javax.swing.JComboBox<String> religion;
    private javax.swing.JButton saveinfo;
    private javax.swing.JComboBox<String> st;
    private javax.swing.JTextField stdname;
    // End of variables declaration//GEN-END:variables
String filename=null;
byte[] studentimg=null;
}
