/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student1;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author w
 */
public class ManageStudent extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudent
     */
    public ManageStudent() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cit = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        religion = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        fatherocc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        stt = new javax.swing.JComboBox<>();
        updateinfo = new javax.swing.JButton();
        nationality = new javax.swing.JComboBox<>();
        mothername = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stdname = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeleteRecord = new javax.swing.JButton();
        rollno = new javax.swing.JTextField();
        search1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cl = new javax.swing.JComboBox<>();
        updatephoto = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_img = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel12.setText("PIN CODE :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 462, -1, 34));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel16.setText("MOTHER'S NAME :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 188, 201, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("EMAIL ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 366, -1, -1));

        cit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE" }));
        cit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                citMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                citMouseEntered(evt);
            }
        });
        cit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citActionPerformed(evt);
            }
        });
        jPanel1.add(cit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 250, 39));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "MALE", "FEMALE", "OTHER", " " }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 320, 246, 34));

        religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "SC", "ST", "OBC", "GEN" }));
        religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionActionPerformed(evt);
            }
        });
        jPanel1.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 321, 244, 32));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel20.setText("FATHER'S OCCUPATION :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 188, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel13.setText("STATE :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, 34));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel15.setText("FATHER'S NAME :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 97, -1, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 134, 243, 124));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel10.setText("NATIONALITY :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 366, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 31, 33));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel19.setText("CASTE :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 276, -1, 38));

        pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinMouseEntered(evt);
            }
        });
        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinKeyTyped(evt);
            }
        });
        jPanel1.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 502, 243, 39));

        aadhar.setToolTipText("enter digits only");
        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        aadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aadharKeyTyped(evt);
            }
        });
        jPanel1.add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 244, 40));

        fatherocc.setToolTipText("enter alphabets only");
        fatherocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatheroccActionPerformed(evt);
            }
        });
        fatherocc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fatheroccKeyTyped(evt);
            }
        });
        jPanel1.add(fatherocc, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 224, 244, 34));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel14.setText("CITY :");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        dob.setDateFormatString("yyyy-MM-dd"); // NOI18N
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 246, 30));

        stt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "Punjab", "Himachal Pradesh", "Jammu and kashmir", "Haryana" }));
        stt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sttMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sttMouseEntered(evt);
            }
        });
        stt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sttActionPerformed(evt);
            }
        });
        jPanel1.add(stt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 246, 39));

        updateinfo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        updateinfo.setText("UPDATE");
        updateinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateinfoActionPerformed(evt);
            }
        });
        jPanel1.add(updateinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, -1));

        nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "Indian", "Canadian", "South Korean", "Australian" }));
        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });
        jPanel1.add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 409, 244, 32));

        mothername.setToolTipText("enter alphabets only");
        mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernameActionPerformed(evt);
            }
        });
        mothername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mothernameKeyTyped(evt);
            }
        });
        jPanel1.add(mothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 226, 246, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 414, 243, 30));

        fathername.setToolTipText("enter alphabets only");
        fathername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernameActionPerformed(evt);
            }
        });
        fathername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fathernameKeyTyped(evt);
            }
        });
        jPanel1.add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 134, 246, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setText("ADDRESS :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 98, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("CONTACT NUMBER :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 276, -1, -1));

        stdname.setToolTipText("Please enter alphabets only");
        stdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdnameActionPerformed(evt);
            }
        });
        stdname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stdnameKeyTyped(evt);
            }
        });
        jPanel1.add(stdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 134, 246, 30));

        contactno.setToolTipText("enter digits only");
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        contactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactnoKeyTyped(evt);
            }
        });
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 318, 234, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setText("AADHAR NUMBER :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setText("GENDER :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setText("DOB :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("STUDENT NAME :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 97, -1, -1));

        DeleteRecord.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        DeleteRecord.setText("DELETE");
        DeleteRecord.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DeleteRecordAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        DeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecordActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 114, -1));
        jPanel1.add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 44, 233, 36));

        search1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search1.setText("SEARCH");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel1.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 41, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SEARCH RECORD BY ROLL NUMBER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 11, -1, -1));

        cl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th" }));
        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 46, 204, 33));

        updatephoto.setText("Update img ");
        updatephoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatephotoActionPerformed(evt);
            }
        });
        jPanel1.add(updatephoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 301, -1, -1));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopPane1.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 163, 149));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 134, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baim-hanif-pYWuOMhtc6k-unsplash.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void citMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citMouseClicked

        if(cit.getSelectedItem().equals("Pathankot"))
        {
            pin.setText("");
            pin.setText("145001");
        }
        if(cit.getSelectedItem().equals("Amritsar"))
        {
            pin.setText("");
            pin.setText("143001");
    }//GEN-LAST:event_citMouseClicked
    }
    private void citMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citMouseEntered

    }//GEN-LAST:event_citMouseEntered

    private void citActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citActionPerformed

    }//GEN-LAST:event_citActionPerformed

    private void religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        homepage l= new homepage();
        l.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void pinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_pinMouseEntered

    private void pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyTyped
        // TODO add your handling code here:
        char k=evt.getKeyChar();
        if(!(Character.isDigit(k)))
        {
            evt.consume();
        }
        if(pin.getText().length()>5)
        {
            evt.consume();
        }
        if(pin.getText().length()<5)
        {
            pin.setBackground(Color.red);
        }
        if(pin.getText().length()==5)
        {
            pin.setBackground(Color.green);
        }
    }//GEN-LAST:event_pinKeyTyped

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharActionPerformed

    private void aadharKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aadharKeyTyped
        // TODO add your handling code here:
        char l=evt.getKeyChar();
        if(!(Character.isDigit(l)))
        {
            evt.consume();
        }
        if(aadhar.getText().length()>11)
        {
            evt.consume();
        }
        if(aadhar.getText().length()<11)
        {
            aadhar.setBackground(Color.red);
        }
        if(aadhar.getText().length()==11)
        {
            aadhar.setBackground(Color.green);
        }
    }//GEN-LAST:event_aadharKeyTyped

    private void fatheroccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatheroccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatheroccActionPerformed

    private void fatheroccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatheroccKeyTyped
        // TODO add your handling code here:
        char b=evt.getKeyChar();
        if((Character.isDigit(b)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_fatheroccKeyTyped

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void sttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sttMouseClicked
        if(stt.getSelectedItem().equals("Punjab"))
        {
            cit.removeAllItems();
            cit.addItem("Pathankot");
            cit.addItem("Amritsar");
            cit.addItem("Jalandhar");
            cit.addItem("Ludhiana");
            cit.addItem("Patiala");
            cit.addItem("Hoshiarpur");
        }

        if(stt.getSelectedItem().equals("Himachal Pradesh"))
        {
            cit.removeAllItems();
            cit.addItem("Chamba");
            cit.addItem("Dharamshala");
            cit.addItem("Shimla");
            cit.addItem("Manali");
            cit.addItem("Solan");
            cit.addItem("Dalhousie");
            cit.addItem("Kullu");
        }
        if(stt.getSelectedItem().equals("Jammu and Kashmir"))
        {
            cit.removeAllItems();
            cit.addItem("Jammu");
            cit.addItem("Katra");
            cit.addItem("Khang");
            cit.addItem("Kulgam");
            cit.addItem("Anantnag");
            cit.addItem("Surankote");
            cit.addItem("Poonch");
            cit.addItem("Akhnoor");
        }
        if(stt.getSelectedItem().equals("Haryana"))
        {
            cit.addItem("Rohtak");
            cit.addItem("Faridabad");
            cit.addItem("Ambala");
            cit.addItem("Sonipat");
            cit.addItem("Hisar");
    }//GEN-LAST:event_sttMouseClicked
    }
    private void sttMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sttMouseEntered
       
    }//GEN-LAST:event_sttMouseEntered

    private void sttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sttActionPerformed

    private void updateinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateinfoActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst;
        ResultSet rs;
        SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
        String date= sf.format(dob.getDate());
        
        if(stdname.getText().equals("")){
      JOptionPane.showMessageDialog(this, "All Field is Requied");
      stdname.requestFocus();
    }
    else if(fathername.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       fathername.requestFocus();
    }
    
     else if(mothername.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       mothername.requestFocus();
    }
     else if(email.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       email.requestFocus();
    }
     else if(nationality.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       nationality.requestFocus();
     }
     else if(cl.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Class");
       cl.requestFocus();
     }
     else if(gender.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Gender");
       gender.requestFocus();
     }
     else if(stt.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select State");
       stt.requestFocus();
     }
     else if(cit.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select City");
       cit.requestFocus();
     }
     else if(religion.getSelectedItem().equals("CHOOSE")){
       JOptionPane.showMessageDialog(this, "Select Cast");
       religion.requestFocus();
     }
     else if(address.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       address.requestFocus();
    }
     else if(fatherocc.getText().equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       fatherocc.requestFocus();
    }
     else if(pin.getText().length()!=6){
        JOptionPane.showMessageDialog(this, "pincode Should be 6 Digit.");
    }
    else if(aadhar.getText().length()!=12){
        JOptionPane.showMessageDialog(this, "Adhar Number Should be 12 Digit.");
     }
     else if(contactno.getText().length()!=10){
        JOptionPane.showMessageDialog(this, "Mobile Number Should be 10 Digit.");
     }
    
    else{ 
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            
            
if(cl.getSelectedItem().equals("1st")){
 pst=con.prepareStatement("update 1st set fathername=?, mothername=?, dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
            
            
            /*pst =con.prepareStatement("update student set student.fathername=1st.fathername,"
             + "student.mothername=1st.mothername, student.class=1st.class ,"
             + "student.dob=1st.dob, student.contact=1st.contact,student.email=1st.email,student.religion=1st.religion,"
             + "student.aadharnumber=1st.aadharnumber,student.nationality=1st.nationality,student.gender=1st.gender,student.state=1st.state,"
             + "student.city=1st.city,student.pin=1st.pin,student.address=1st.address,student.fatheroccupation=1st.fatheroccupation,student.name=1st.name,"
             + "student.studentimg=1st.studentimg  where student.rollno=1st.rolllno");
            pst.setString(1, rollno.getText());
            pst.executeUpdate();*/
           
}
else if(cl.getSelectedItem().equals("2nd")){
      pst=con.prepareStatement("update 2nd set fathername=?, mothername=?,dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
            
            
         
}
else if(cl.getSelectedItem().equals("3rd")){
    pst=con.prepareStatement("update 3rd set fathername=?, mothername=?, dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
            
          
}
else if(cl.getSelectedItem().equals("4th")){
    pst=con.prepareStatement("update 4th set fathername=?, mothername=?, dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("5th")){
     pst=con.prepareStatement("update 5th set fathername=?, mothername=?,dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("6th")){
   pst=con.prepareStatement("update 6th set fathername=?, mothername=?, dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("7th")){
     pst=con.prepareStatement("update 7th set fathername=?, mothername=?,dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("8th")){
     pst=con.prepareStatement("update 8th set fathername=?, mothername=?, dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("9th")){
     pst=con.prepareStatement("update 9th set fathername=?, mothername=?,dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}
else if(cl.getSelectedItem().equals("10th")){
    pst=con.prepareStatement("update 10th set fathername=?, mothername=?,dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16,rollno.getText());
            pst.executeUpdate();
}

else{
    JOptionPane.showMessageDialog(this,"STUDENT DATA NOT ADDED INTO CLASS");
}
            pst=con.prepareStatement("update student set fathername=?, mothername=?,dob=? ,contact=? ,email=?, religion=?, aadharnumber=?, nationality=? ,gender=? ,state=? ,city=? ,pin=? ,address=? ,fatheroccupation=?, name=? where class=? AND rollno=?");
            pst.setString(1, fathername.getText());
            pst.setString(2, mothername.getText());
            pst.setString(3,date);
            pst.setString(4,contactno.getText());
            pst.setString(5, email.getText());
            pst.setString(6,(String) religion.getSelectedItem());
            pst.setString(7,aadhar.getText());
            pst.setString(8,nationality.getItemAt(nationality.getSelectedIndex()));
            pst.setString(9, gender.getItemAt(gender.getSelectedIndex()));
            pst.setString(10, stt.getItemAt(stt.getSelectedIndex()));
            pst.setString(11, cit.getItemAt(cit.getSelectedIndex()));
            pst.setString(12,pin.getText());
            pst.setString(13,address.getText());
            pst.setString(14, fatherocc.getText());
            pst.setString(15, stdname.getText());
            pst.setString(16, cl.getItemAt(cl.getSelectedIndex()));
             pst.setString(17,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated");
        }    
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
       
    }//GEN-LAST:event_updateinfoActionPerformed

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityActionPerformed

    private void mothernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernameActionPerformed

    private void mothernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mothernameKeyTyped
        // TODO add your handling code here:
        char d=evt.getKeyChar();
        if((Character.isDigit(d)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_mothernameKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fathernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathernameActionPerformed

    private void fathernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fathernameKeyTyped
        // TODO add your handling code here:
        char a=evt.getKeyChar();
        if((Character.isDigit(a)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_fathernameKeyTyped

    private void stdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdnameActionPerformed

    private void stdnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdnameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if((Character.isDigit(c)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_stdnameKeyTyped

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void contactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyTyped
        // TODO add your handling code here:
        char j=evt.getKeyChar();
        if(!(Character.isDigit(j)))
        {
            evt.consume();
        }
        if(contactno.getText().length()>9)
        {
            evt.consume();
        }
        if(contactno.getText().length()<9)
        {
            contactno.setBackground(Color.red);
        }
        if(contactno.getText().length()==9)
        {
            contactno.setBackground(Color.green);
        }
    }//GEN-LAST:event_contactnoKeyTyped

    private void DeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecordActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement pst;
        ResultSet rs;
        SimpleDateFormat sf = new SimpleDateFormat("yyyy/MM/dd");
        
            try {
             
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
             
                
         if(cl.getSelectedItem().equals("1st")){ 
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 1st where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
                pst=con.prepareStatement("DELETE FROM resulte1st2nd where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
              
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");
         }
         else if(cl.getSelectedItem().equals("2nd")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 2nd where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
                pst=con.prepareStatement("DELETE FROM resulte1st2nd where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
               
                 if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }

         else if(cl.getSelectedItem().equals("3rd")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 3rd where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
                pst=con.prepareStatement("DELETE FROM resulte3rd4th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
              
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }
         else if(cl.getSelectedItem().equals("4th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 4th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
                pst=con.prepareStatement("DELETE FROM resulte4th5th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
              
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }
         else if(cl.getSelectedItem().equals("5th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
             
                pst=con.prepareStatement("DELETE FROM 5th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
                pst=con.prepareStatement("DELETE FROM resulte4th5th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
                
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");          
         }
         else if(cl.getSelectedItem().equals("6th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 6th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
               
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }
         else if(cl.getSelectedItem().equals("7th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 7th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
             
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }
         else if(cl.getSelectedItem().equals("8th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 8th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
               
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }
         else if(cl.getSelectedItem().equals("9th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 9th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
          
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         } 
         else if(cl.getSelectedItem().equals("10th")){
             int  yes=JOptionPane.showConfirmDialog(this,"Are you sure? it will allso delete its result of student ","DELETE",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                pst=con.prepareStatement("DELETE FROM 10th where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
              
                if(yes==JOptionPane.YES_OPTION)
                JOptionPane.showMessageDialog(this, "deleted successfull");            
         }
                pst=con.prepareStatement("DELETE FROM student where aadharnumber=?");
                pst.setString(1,aadhar.getText());
                pst.executeUpdate();
               
               
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_DeleteRecordActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
       
        
        PreparedStatement pst = null;
        Statement st = null;
        ResultSet rs = null;
       
            try {
                  java.sql.Connection con;
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo", "root", "123456");
                  pst = con.prepareStatement("Select * from student where rollno=? AND class=?");
                  pst.setString(1, rollno.getText());
                  pst.setString(2,cl.getItemAt(cl.getSelectedIndex()));
                  //String date=rs.getString("dob");
                rs = pst.executeQuery();
                if (rs.next()) {
                stdname.setText(rs.getString("name"));
                fathername.setText(rs.getString("fathername"));
                address.setText(rs.getString("address"));
                mothername.setText(rs.getString("mothername"));
                fatherocc.setText(rs.getString("fatheroccupation"));
                contactno.setText(rs.getString("contact"));
                email.setText(rs.getString("email"));
                aadhar.setText(rs.getString("aadharnumber"));
                gender.setSelectedItem(rs.getString("gender"));
                religion.setSelectedItem(rs.getString("religion"));
                nationality.setSelectedItem(rs.getString("nationality"));
                stt.setSelectedItem(rs.getString("state"));
                ((JTextField)dob.getDateEditor().getUiComponent()).setText(rs.getString("dob"));
                cit.addItem(rs.getString("city"));
                pin.setText(rs.getString("pin"));
              
                
                 byte[] img = rs.getBytes("studentimg");
                 ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
                 lbl_img.setIcon(imageIcon);
          
                }
           else{
                 JOptionPane.showMessageDialog(this, "Record not found");
                 
                lbl_img.setIcon(null);
                cit.removeAllItems();
                stdname.setText("");
                fathername.setText("");
                address.setText("");
                mothername.setText("");
                fatherocc.setText("");
                contactno.setText("");
                email.setText("");
                pin.setText("");
                aadhar.setText("");
                gender.setSelectedIndex(0);
                religion.setSelectedIndex(0);
                nationality.setSelectedIndex(0);
                stt.setSelectedIndex(0);
                cit.setSelectedIndex(0);
                dob.setDate(null);
                rollno.setText("");
                cl.setSelectedIndex(0);
                
            }
            
            } 
            
            catch (SQLException | ClassNotFoundException ex) {
        
            }
          
    }//GEN-LAST:event_search1ActionPerformed

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void updatephotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatephotoActionPerformed
        // TODO add your handling code here:
        
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
        lbl_img.setIcon(imageIcon);
        
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            studentimg = bos.toByteArray();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");
            PreparedStatement pst;
            ResultSet rs;
            pst=con.prepareStatement("update student set studentimg=? where aadharnumber=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,aadhar.getText());
            pst.executeUpdate();
            
         if(cl.getSelectedItem().equals("1st")){   
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");
         }
         else if(cl.getSelectedItem().equals("2nd")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("3rd")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("4th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("5th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("6th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("7th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("8th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
         else if(cl.getSelectedItem().equals("9th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         } 
         else if(cl.getSelectedItem().equals("10th")){
            pst=con.prepareStatement("update 1st set studentimg=? where rollno=?");
            pst.setBytes(1,studentimg);
            pst.setString(2,rollno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Img Updated");            
         }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
}      
    }//GEN-LAST:event_updatephotoActionPerformed

    private void DeleteRecordAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DeleteRecordAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRecordAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteRecord;
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextArea address;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> cit;
    private javax.swing.JComboBox<String> cl;
    private javax.swing.JTextField contactno;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fathername;
    private javax.swing.JTextField fatherocc;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField mothername;
    private javax.swing.JComboBox<String> nationality;
    private javax.swing.JTextField pin;
    private javax.swing.JComboBox<String> religion;
    private javax.swing.JTextField rollno;
    private javax.swing.JButton search1;
    private javax.swing.JTextField stdname;
    private javax.swing.JComboBox<String> stt;
    private javax.swing.JButton updateinfo;
    private javax.swing.JButton updatephoto;
    // End of variables declaration//GEN-END:variables
String filename=null;
byte[] studentimg=null;
String state=null;
}
