/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student1;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author w
 */
public class Showresulte extends javax.swing.JFrame {
 static String name;
 static String clas;
 static String roll;
 static String addh;
    /**
     * Creates new form Showresulte
     */
    public Showresulte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cl = new javax.swing.JComboBox<>();
        rollno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        engText = new javax.swing.JTextField();
        matheText = new javax.swing.JTextField();
        hindiText = new javax.swing.JTextField();
        evsText = new javax.swing.JTextField();
        gkText = new javax.swing.JTextField();
        artText = new javax.swing.JTextField();
        peText = new javax.swing.JTextField();
        csText = new javax.swing.JTextField();
        sText = new javax.swing.JTextField();
        ssText = new javax.swing.JTextField();
        pText = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        pengText = new javax.swing.JTextField();
        pmatheText = new javax.swing.JTextField();
        phindiText = new javax.swing.JTextField();
        pevsText = new javax.swing.JTextField();
        pgkText = new javax.swing.JTextField();
        partText = new javax.swing.JTextField();
        ppeText = new javax.swing.JTextField();
        pcsText = new javax.swing.JTextField();
        psText = new javax.swing.JTextField();
        pssText = new javax.swing.JTextField();
        ppText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th" }));
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 16, 102, 33));

        rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoActionPerformed(evt);
            }
        });
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 16, 374, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Roll no");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 24, -1, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 16, -1, 33));
        getContentPane().add(engText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 194, 220, -1));

        matheText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matheTextActionPerformed(evt);
            }
        });
        getContentPane().add(matheText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 282, 220, -1));
        getContentPane().add(hindiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 358, 220, -1));

        evsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evsTextActionPerformed(evt);
            }
        });
        getContentPane().add(evsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 426, 220, -1));
        getContentPane().add(gkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 500, 220, -1));
        getContentPane().add(artText, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 580, 220, -1));
        getContentPane().add(peText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 194, 294, -1));
        getContentPane().add(csText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 272, 294, -1));

        sText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTextActionPerformed(evt);
            }
        });
        getContentPane().add(sText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 353, 294, -1));
        getContentPane().add(ssText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 426, 294, -1));
        getContentPane().add(pText, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 500, 294, -1));

        clear.setText("Clear");
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 630, -1, -1));

        save.setText("Update");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, -1, -1));
        getContentPane().add(pengText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 194, 77, -1));

        pmatheText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmatheTextActionPerformed(evt);
            }
        });
        getContentPane().add(pmatheText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 282, 77, -1));
        getContentPane().add(phindiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 358, 77, -1));
        getContentPane().add(pevsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 426, 77, -1));
        getContentPane().add(pgkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 500, 77, -1));

        partText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTextActionPerformed(evt);
            }
        });
        getContentPane().add(partText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 580, 77, -1));
        getContentPane().add(ppeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 194, 80, -1));
        getContentPane().add(pcsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 272, 80, -1));
        getContentPane().add(psText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 353, 80, -1));
        getContentPane().add(pssText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 426, 80, -1));
        getContentPane().add(ppText, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 500, 80, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parctical");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 172, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parctical");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 172, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-page-option.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 16, 40, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("English");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 172, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mathematics");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 248, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hindi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 336, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enviromental Studies");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 392, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("General Knowledge");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 466, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Art and Craft");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 540, -1, 22));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Health and Physical Education");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 172, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Computer Science");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 250, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Science");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 325, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Social Science");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 392, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Punjabi");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 466, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 220, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 240, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 240, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("aadhar no");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("class");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("rollno");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("name");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 40, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rg (1).jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst=null;
        java.sql.Statement st=null;
        ResultSet rs=null;
        java.sql.Connection con=null;
       
        if(cl.getSelectedItem().equals("1st") || cl.getSelectedItem().equals("2nd")){
            /*engText.setEditable(true);
            pengText.setEditable(true);
            hindiText.setEditable(true);
            phindiText.setEditable(true);
            artText.setEditable(true);
            partText.setEditable(true);
            matheText.setEditable(true);
            pmatheText.setEditable(true);
            gkText.setEditable(true);
            pgkText.setEditable(true);*/
            evsText.setEditable(false);
            pevsText.setEditable(false);
            peText.setEditable(false);
            ppeText.setEditable(false);
            csText.setEditable(false);
            pcsText.setEditable(false);
            sText.setEditable(false);
            psText.setEditable(false);
            ssText.setEditable(false);
            pssText.setEditable(false);
            pText.setEditable(false);
            ppText.setEditable(false);
            
            
       
            try {
               
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo", "root", "123456");
                  pst = con.prepareStatement("Select * from resulte1st2nd where class=? AND rollno=?");
                   pst.setString(1, cl.getItemAt(cl.getSelectedIndex()));
                  pst.setString(2, rollno.getText());
                
                rs = pst.executeQuery();
                if (rs.next()){
                 jTextField1.setText(rs.getString("name"));
                 jTextField2.setText(rs.getString("class"));
                 jTextField3.setText(rs.getString("rollno"));
                 jTextField4.setText(rs.getString("aadharnumber"));
                 engText.setText(rs.getString("Eng"));
                 hindiText.setText(rs.getString("hindi"));
                 artText.setText(rs.getString("Art"));
                 matheText.setText(rs.getString("Math"));
                 gkText.setText(rs.getString("GK"));
                 pengText.setText(rs.getString("peng"));
                 phindiText.setText(rs.getString("phindi"));
                 pmatheText.setText(rs.getString("pmath"));
                 partText.setText(rs.getString("part"));
                 pgkText.setText(rs.getString("pgk"));
                }
           
            } catch (SQLException | ClassNotFoundException ex) {
                //Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "record not found");
            }
          
        }
        else if (cl.getSelectedItem().equals("3rd") || cl.getSelectedItem().equals("4th")) {
            engText.setEditable(true);
            pengText.setEditable(true);
            hindiText.setEditable(true);
            phindiText.setEditable(true);
            artText.setEditable(false);
            partText.setEditable(false);
            matheText.setEditable(true);
            pmatheText.setEditable(true);
            gkText.setEditable(true);
            pgkText.setEditable(true);
            evsText.setEditable(true);
            pevsText.setEditable(true);
            peText.setEditable(false);
            ppeText.setEditable(false);
            csText.setEditable(false);
            pcsText.setEditable(false);
            sText.setEditable(false);
            psText.setEditable(false);
            ssText.setEditable(false);
            pssText.setEditable(false);
            pText.setEditable(false);
            ppText.setEditable(false);

        }
        else if (cl.getSelectedItem().equals("5th") || cl.getSelectedItem().equals("6th")) {
            engText.setEditable(true);
            pengText.setEditable(true);
            hindiText.setEditable(true);
            phindiText.setEditable(true);
            artText.setEditable(false);
            partText.setEditable(false);
            matheText.setEditable(true);
            pmatheText.setEditable(true);
            gkText.setEditable(false);
            pgkText.setEditable(false);
            evsText.setEditable(true);
            pevsText.setEditable(true);
            peText.setEditable(false);
            ppeText.setEditable(false);
            csText.setEditable(false);
            pcsText.setEditable(false);
            sText.setEditable(true);
            psText.setEditable(true);
            ssText.setEditable(true);
            pssText.setEditable(true);
            pText.setEditable(false);
            ppText.setEditable(false);

        }
        else if (cl.getSelectedItem().equals("7th") || cl.getSelectedItem().equals("8th")) {
            engText.setEditable(true);
            pengText.setEditable(true);
            hindiText.setEditable(true);
            phindiText.setEditable(true);
            artText.setEditable(false);
            partText.setEditable(false);
            matheText.setEditable(true);
            pmatheText.setEditable(true);
            gkText.setEditable(false);
            pgkText.setEditable(false);
            evsText.setEditable(false);
            pevsText.setEditable(false);
            peText.setEditable(false);
            ppeText.setEditable(false);
            csText.setEditable(false);
            pcsText.setEditable(false);
            sText.setEditable(true);
            psText.setEditable(true);
            ssText.setEditable(true);
            pssText.setEditable(true);
            pText.setEditable(false);
            ppText.setEditable(false);

        }
        else if (cl.getSelectedItem().equals("9th") || cl.getSelectedItem().equals("10th")) {
            engText.setEditable(true);
            pengText.setEditable(true);
            hindiText.setEditable(true);
            phindiText.setEditable(true);
            artText.setEditable(false);
            partText.setEditable(false);
            matheText.setEditable(true);
            pmatheText.setEditable(true);
            gkText.setEditable(false);
            pgkText.setEditable(false);
            evsText.setEditable(false);
            pevsText.setEditable(false);
            peText.setEditable(true);
            ppeText.setEditable(true);
            csText.setEditable(false);
            pcsText.setEditable(false);
            sText.setEditable(true);
            psText.setEditable(true);
            ssText.setEditable(true);
            pssText.setEditable(true);
            pText.setEditable(false);
            ppText.setEditable(false);

        }
    }//GEN-LAST:event_searchActionPerformed

    private void matheTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matheTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matheTextActionPerformed

    private void evsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evsTextActionPerformed

    private void sTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTextActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        Statement st=null;
        PreparedStatement pst=null;

         name= jTextField1.getText() ;
         clas= jTextField2.getText() ;
         roll= jTextField3.getText() ;
         addh= jTextField4.getText() ;

        // System.out.print(name);
        // System.out.print(clas);
        // System.out.print(roll);
        // System.out.print(addh);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","123456");

            if(cl.getSelectedItem().equals("1st") || cl.getSelectedItem().equals("2nd")){
                pst=con.prepareStatement("update resulte1st2nd set Eng=?,hindi=?,Math=?,Art=?,GK=?,peng=?,phindi=?,pmath=?,part=?,pgk=? where class=? and rollno=?");
                pst.setString(1,engText.getText());
                pst.setString(2, hindiText.getText());
                pst.setString(3,matheText.getText());
                pst.setString(4,artText.getText());
                pst.setString(5,gkText.getText());
                pst.setString(6, pengText.getText());
                pst.setString(7, phindiText.getText());
                pst.setString(8, pmatheText.getText());
                pst.setString(9,partText.getText());
                pst.setString(10,pgkText.getText());
                pst.setString(11, clas);
                pst.setString(12, roll);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "update");
            }
            else if (cl.getSelectedItem().equals("3rd") || cl.getSelectedItem().equals("4th")){
                pst=con.prepareStatement("update resulte3rd4th set Eng=?,hindi=?,Mathe=?,GK=?,evs=?,peng=?,phindi=?,pmathe=?,pgk=?,pevs=? where class=? and rollno=?");
                pst.setString(1,engText.getText());
                pst.setString(2, hindiText.getText());
                pst.setString(3,matheText.getText());
                pst.setString(4,gkText.getText());
                pst.setString(5,evsText.getText());
                pst.setString(6, pengText.getText());
                pst.setString(7, phindiText.getText());
                pst.setString(8, pmatheText.getText());
                pst.setString(9,pgkText.getText());
                pst.setString(10,pevsText.getText());
                pst.setString(11, clas);
                pst.setString(12, roll);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "saved");
            }
            else if (cl.getSelectedItem().equals("5th") || cl.getSelectedItem().equals("6th")){
                pst=con.prepareStatement("insert into resulte5th6th(name,class,rollno,aadharnumber,Eng,hindi,Math,Science,evs,socialscience,peng,phindi,pmath,pscience,pevs,psocialscience)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, name);
                pst.setString(2, clas);
                pst.setString(3, roll);
                pst.setString(4,addh);
                pst.setString(5,engText.getText());
                pst.setString(6, hindiText.getText());
                pst.setString(7,matheText.getText());
                pst.setString(8,sText.getText());
                pst.setString(9,evsText.getText());
                pst.setString(10, ssText.getText());
                pst.setString(11, pengText.getText());
                pst.setString(12, phindiText.getText());
                pst.setString(13,pmatheText.getText());
                pst.setString(14,psText.getText());
                pst.setString(15,pevsText.getText());
                pst.setString(16,pssText.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "saved");
            }
            else if (cl.getSelectedItem().equals("7th") || cl.getSelectedItem().equals("8th")){
                pst=con.prepareStatement("insert into resulte7th8th(name,class,rollno,aadharnumber,Eng,hindi,Math,Science,socialscience,peng,phindi,pmath,pscience,psocialscience)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, name);
                pst.setString(2, clas);
                pst.setString(3, roll);
                pst.setString(4,addh);
                pst.setString(5,engText.getText());
                pst.setString(6, hindiText.getText());
                pst.setString(7,matheText.getText());
                pst.setString(8,sText.getText());
                pst.setString(9,ssText.getText());
                pst.setString(10, pengText.getText());
                pst.setString(11, phindiText.getText());
                pst.setString(12, pmatheText.getText());
                pst.setString(13,psText.getText());
                pst.setString(14,pssText.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "saved");
            }
            else if (cl.getSelectedItem().equals("9th") || cl.getSelectedItem().equals("10th")){
                pst=con.prepareStatement("insert into resulte9th10th(name,class,rollno,aadharnumber,Eng,hindi,Math,Science,socialscience,physicaleducation,peng,phindi,pmath,pscience,psocialscience,pphysicaleducation)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, name);
                pst.setString(2, clas);
                pst.setString(3, roll);
                pst.setString(4,addh);
                pst.setString(5,engText.getText());
                pst.setString(6, hindiText.getText());
                pst.setString(7,matheText.getText());
                pst.setString(8,sText.getText());
                pst.setString(9,ssText.getText());
                pst.setString(10,peText.getText());
                pst.setString(11, pengText.getText());
                pst.setString(12, phindiText.getText());
                pst.setString(13, pmatheText.getText());
                pst.setString(14,psText.getText());
                pst.setString(15,pssText.getText());
                pst.setString(16,ppeText.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "saved");
            }
        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveActionPerformed

    private void pmatheTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmatheTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmatheTextActionPerformed

    private void partTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partTextActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       // DefaultTableModel RecordTable= (DefaultTableModel) jTable1.getModel();
       // RecordTable.setRowCount(0);
       
        jTextField1.getText() ;
        jTextField2.getText() ;
        jTextField3.getText() ;
        jTextField4.getText() ;
        rollno.setText(null);
        cl.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        printresult pt  = new printresult();
        pt.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        homepage hm = new homepage();
        hm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Showresulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Showresulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Showresulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Showresulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Showresulte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artText;
    private javax.swing.JComboBox<String> cl;
    private javax.swing.JButton clear;
    private javax.swing.JTextField csText;
    private javax.swing.JTextField engText;
    private javax.swing.JTextField evsText;
    private javax.swing.JTextField gkText;
    private javax.swing.JTextField hindiText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField matheText;
    private javax.swing.JTextField pText;
    private javax.swing.JTextField partText;
    private javax.swing.JTextField pcsText;
    private javax.swing.JTextField peText;
    private javax.swing.JTextField pengText;
    private javax.swing.JTextField pevsText;
    private javax.swing.JTextField pgkText;
    private javax.swing.JTextField phindiText;
    private javax.swing.JTextField pmatheText;
    private javax.swing.JTextField ppText;
    private javax.swing.JTextField ppeText;
    private javax.swing.JTextField psText;
    private javax.swing.JTextField pssText;
    private javax.swing.JTextField rollno;
    private javax.swing.JTextField sText;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField ssText;
    // End of variables declaration//GEN-END:variables
}
